---
name: flutter_riverpod_projects
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  freezed_annotation: ^0.12.0
  http: ^0.12.2
  riverpod: ^0.12.2
  json_serializable: ^3.5.1
  flutter_riverpod: ^0.12.2
  geolocator: ^6.1.14


dev_dependencies:
  build_runner: ^1.10.13
  freezed: ^0.12.7
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
